### ISSUE TITLE
MovieManagerlist cosmetics

### ISSUE THREAD

**Issue by RobvanderDoes** [ims21/MovieManager#20]
In the latest version:
1- there are no more (unchecked) checkboxes, which is ugly.
2- it is no longer possible to 'skin' the fonts (hence font is now very small).
![MovieList-01](https://user-images.githubusercontent.com/1040294/68472157-2ae3c280-0220-11ea-955e-17c9c4a3d371.jpg)

**Comment by ims21** [comment]
Im sorry, not my fault... there were some changes in PLi, use 1 line for font and 2 parameters as are there in PLi-FullHD.skin  for "ImsSelect..." items to your skin  ((https://github.com/ims21/skin-PLiHD/commit/39909386b26c0b114cd28d16bac48cbf8f575bfd)).

**Comment by RobvanderDoes** [comment]
Thanks.
Could you please explain what the (8) parameters are for exactly?

**Comment by ims21** [comment]
ImsSelectionListDescr ... 46,4,1000,45  text rectangle ... x,y, width, height
ImsSelectionListLock ... 0,2,36,36 icone position and size x,y, width, height

**Comment by RobvanderDoes** [comment]
Thanks.
